version: "3.8"

services:
  bot:
    build: .
    container_name: software_bot
    restart: always
    environment:
      # Credenciales de Telegram (se llenan en Dokploy)
      - API_ID=${API_ID}
      - API_HASH=${API_HASH}
      - BOT_TOKEN=${BOT_TOKEN}
      - ADMIN_ID=${ADMIN_ID}
      - PUBLIC_CHANNEL_ID=${PUBLIC_CHANNEL_ID}
      - PRIVATE_BACKUP_CHANNEL_ID=${PRIVATE_BACKUP_CHANNEL_ID}
      
      # URL de la base de datos interna usando el servicio "db"
      - DB_URL=postgresql://myuser:mypassword@db:5432/bot_data
      - MIN_DISK_SPACE_GB=${MIN_DISK_SPACE_GB:-15}
      - PROXY_URL=${PROXY_URL}
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15-alpine
    container_name: software_bot_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: bot_data
    volumes:
      - bot_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d bot_data"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  bot_postgres_data:
