version: '3.8'

services:
  telegram-api:
    image: aiogram/telegram-bot-api:latest
    container_name: telegram-local-api
    restart: unless-stopped
    environment:
      TELEGRAM_API_ID: ${API_ID}
      TELEGRAM_API_HASH: ${API_HASH}
      TELEGRAM_LOCAL: "true"
    volumes:
      - bot_downloads:/downloads
    expose:
      - "8081"

  bot:
    build: .
    container_name: distribucion_bot
    restart: unless-stopped
    environment:
      API_ID: ${API_ID}
      API_HASH: ${API_HASH}
      BOT_TOKEN: ${BOT_TOKEN}
      ADMIN_ID: ${ADMIN_ID}
      PUBLIC_CHANNEL_ID: ${PUBLIC_CHANNEL_ID}
      PRIVATE_BACKUP_CHANNEL_ID: ${PRIVATE_BACKUP_CHANNEL_ID}
      DB_URL: postgresql://myuser:mypassword@db:5432/bot_data
      PROXY_URL: ${PROXY_URL}
      TELEGRAM_API_BASE_URL: http://telegram-api:8081/bot
    depends_on:
      - db
      - telegram-api
    volumes:
      - bot_downloads:/app/downloads

  db:
    image: postgres:15-alpine
    container_name: distribucion_bot_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: bot_data
    volumes:
      - bot_postgres_data4:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d bot_data"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  bot_postgres_data4:
  bot_downloads:
